### ISSUE TITLE
BT580

### ISSUE THREAD

**Issue by bethgocs** [bkbilly/medisanabp_ble#3]
Hello,

for the BT580 I have to change the manufacturer_id to 31256...

/manifest.json
{
  "domain": "medisanabp_ble",
  "name": "Medisana Blood Pressure BLE",
  "bluetooth": [
    {
      "manufacturer_id": 31256,
      "connectable": true
    },
    {
      "local_name": "1872B",
      "connectable": true
    }
  ],

**Comment by bkbilly** [comment]
Thank you for letting me know about this.
I'll add support for your device.

**Comment by de-andrei** [comment]
@bethgocs, how did you get manufacturer_id to 31256? I have problem with my bu 575 :(
